# Generated by Django 4.0.4 on 2022-06-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega7', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='User',
        ),
    ]
