# Generated by Django 4.0.4 on 2022-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega7', '0002_rename_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default='jose', max_length=40),
            preserve_default=False,
        ),
    ]
